### ISSUE TITLE
Send notifications to active users

### ISSUE THREAD

**Issue by stachern** [stachern/bseu_schedule#2] opened 2013-03-14 22:44 UTC
Ask to re-login to the app with oauth2 and grant access to their calendars.

**Comment by dskecse** [comment] 2023-09-25 09:41
NOTE: This should be done right after we've migrated from the old gdata Calendar API v2 to the new Google Calendar API v3 as part of https://github.com/stachern/bseu_schedule/issues/1.

**Comment by dskecse** [comment] 2023-10-24 18:34
@stachern hey, hope you're doing fine! I submitted the app's [OAuth consent screen](https://console.cloud.google.com/apis/credentials/consent?project=bseu-api) for verification early this month and verified the app's URL prefix in Google Search Console as described [here](https://www.googlecloudcommunity.com/gc/Serverless/Default-App-Engine-domain-verification-issue/m-p/649947#M2397), but it seems like this was not enough and the Domain verification is still required smh. I guess, I might be lacking some permissions, since you were the original author of the app, so I'm wondering if you could double-check, whether you can verify the `bseu-api.appspot.com` domain in the Search Console? thanks a bunch anyway

**Comment by stachern** [comment] 2023-10-31 02:23
Seems like there's maybe a manual review queue for apps using sensitive
scopes (
https://developers.google.com/identity/protocols/oauth2/production-readiness/sensitive-scope-verification)
Maybe additional context in request may speed up the resolution (e.g. link
to github or a demo screencast). In general a resubmission may help now
that domain-prefix is verified (btw, I did the same, and I also deleted an
"unverified" search console entry for the same appspot domain). Other than
that I'm out of ideas.

And did I say I'm VERY surprised to see this still alive and resurrected?
haha

**Comment by dskecse** [comment] 2023-10-31 06:48
@stachern yep, there's a manual review queue for such apps, and I already added all the necessary info prior to submitting the app for verification early in October, including a privacy policy page, a video explanation, a written explanation for the need to have sensitive scopes and also verified the url prefix by adding a `google-site-verification` meta tag, as I've explained [in this issue](https://github.com/stachern/bseu_schedule/issues/14), so there's no need for the resubmission. And the only thing that keeps us from unblocking the manual consent screen verification process is an unverified domain property.

![Screenshot 2023-10-31 at 09 30 46](https://github.com/stachern/bseu_schedule/assets/1451690/3769d5c4-3c5d-42dd-9634-1d870e93e5ef)

I actually got a [reply](https://www.googlecloudcommunity.com/gc/Serverless/Default-App-Engine-domain-verification-issue/m-p/656549/highlight/true#M2467) to my question on Google Cloud Community this Friday, saying I may need to reach out to Google's Trust and Safety team or contact Google Domains regarding this issue, so I'll do both now.

> And did I say I'm VERY surprised to see this still alive and resurrected?

haha, so am I, due to the fact I've finally carved out some time to update the app 😉

**Comment by dskecse** [comment] 2023-10-31 07:38
@stachern I'm wondering if you can see the app's domain listed on the [Google Domains page](https://domains.google.com/registrar/)?

**Comment by dskecse** [comment] 2023-10-31 07:47
btw, I just talked to Google Domains support, and here's what they replied with:

![Screenshot 2023-10-31 at 10 36 22](https://github.com/stachern/bseu_schedule/assets/1451690/fd505a50-1e9b-4c87-b4a4-33a28f054862)
![Screenshot 2023-10-31 at 10 36 46](https://github.com/stachern/bseu_schedule/assets/1451690/e04f9b59-4ae2-493d-955c-4a6ea465a0d2)

**Comment by stachern** [comment] 2023-10-31 07:59
Judging by support reps reply appspot.com issued domains weren't in her
playbook. I'll see if I can find something internally on this subject
tomorrow (I doubt).

I do not see this on Google domains, but I do see it as verified in Search
Console. Well, if this is indeed the main blocker, you could get a proper
domain where you can control the DNS record. And make an old appspot one do
a redirect.

QQ: did you file oath request before or after doing Search Console
verification? Wonder if
it got blocked before it got verified on SC

Hardcore option: have bseu make a subdomain for the app (it makes sense
though!) if you still in touch with someone there. Looks like things are
moving slow enough there for it to take another decade :)

**Comment by dskecse** [comment] 2023-10-31 08:14
@stachern yeah, I left adding a custom domain as a last resort.

As for your question, I filed the OAuth request after the Search Console verification, so the URL prefix has already been verified on SC.

I'm in touch with EV there, but, honestly, I doubt that anyone else will even consider adding a subdomain for the app. Although it's still better than having to pay for a custom domain 😄

**Comment by dskecse** [comment] 2023-11-03 11:31
UPD: Google's Trust and Safety team has finally replied to my email regarding the domain owner verification issue, and it looks like the issue is now gone. They've added a couple of other required actions from our side, but seem to be minor, so I'll handle those soon.

**Comment by dskecse** [comment] 2023-11-19 15:54
UPD: I'm thrilled to share that I've received an email from Google's Trust and Safety team today saying our app's OAuth verification request has been granted!

![Screenshot 2023-11-19 at 18 49 39](https://github.com/stachern/bseu_schedule/assets/1451690/f699524c-e61f-414f-94e7-3787a16ee840)
![Screenshot 2023-11-19 at 18 53 58](https://github.com/stachern/bseu_schedule/assets/1451690/f8e5584a-4590-47b9-ba4f-3f34ab8b3e25)

**Comment by dskecse** [comment] 2023-11-20 15:42
UPD: Closing this issue as I've just sent an email to 50 active users as part of this [announcement task](https://github.com/stachern/bseu_schedule/commit/e54af2293b249ec6dad9c45e480d4b4c04879195).

**Closed by dskecse** 2023-11-20 15:42 UTC
Labels: enhancement
